/**
 * Purchase Order Entry — BRD "Purchase Inward Part -1", section 2 (Purchase Order
 * Screen Layout) and section 3 (Purchase Order Approval).
 *
 * The page is a DATA-ENTRY SURFACE, not a second pricing engine. It collects the
 * header and the item lines and saves a real Purchase Order through the ordinary
 * document API, so ERPNext computes net rate, tax, discount and every total exactly
 * as it does anywhere else; the Summary card then reads those numbers back off the
 * saved document. Re-implementing that arithmetic here would give the site two
 * answers for the same order.
 *
 * Approval (BRD 3) is drawn from alpinos.purchase.purchase_order_approval, which owns
 * the transition table, so a button can never be offered here and refused there.
 *
 * Design language matches the other alpinos entry pages: eso-card / eso-card-title /
 * eso-fld / alp-scroll / alp-actions, all from public/css/alpinos_pages.css.
 */

// A Datetime straight out of the database carries microseconds
// (2026-09-06 07:20:44.774097). frappe.datetime.validate parses strictly against
// YYYY-MM-DD HH:mm:ss, so the control rejects the value, raises a msgprint and
// blanks the field. Trim the fraction before any value reaches a control.
// var, not const: desk pages are re-evaluated on navigation.
var ALP_TRIM_MICROSECONDS = function (v) {
	if (typeof v !== 'string') return v;
	var m = v.match(/^(\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2})\.\d+$/);
	return m ? m[1] : v;
};

// BRD 2.1.1 PO Type. Mirrors alpinos.purchase.constants.INWARD_TYPES.
var PO_INWARD_TYPES = ['RM', 'PM', 'FG', 'MM'];

frappe.pages['purchase_order_entry'].on_page_load = function (wrapper) {
	var page = frappe.ui.make_app_page({
		parent: wrapper,
		title: 'Purchase Order Entry',
		single_column: true,
	});
	page.main.html(frappe.render_template('purchase_order_entry'));
	wrapper.po_entry = new PurchaseOrderEntry(page);
};

frappe.pages['purchase_order_entry'].on_page_show = function (wrapper) {
	if (wrapper.po_entry) wrapper.po_entry.handle_route_entry();
};

var PurchaseOrderEntry = class {
	constructor(page) {
		this.page = page;
		this.wrapper = $(page.main);
		this.fields = {};
		this.docname = null;
		this.doc = null;
		this.items = [];
		this.setup();
	}

	setup() {
		this.make_header_fields();
		this.make_supplier_fields();
		this.make_shipment_fields();
		this.make_summary_fields();
		this.make_approval_fields();
		this.bind_events();
		this.make_actions();
	}

	// ------------------------------------------------------------- helpers

	_ctl(selector, df, value) {
		const parent = this.wrapper.find(selector);
		if (!parent.length) return null;
		parent.empty();
		const c = frappe.ui.form.make_control({
			df: Object.assign({ fieldtype: 'Data' }, df),
			parent: parent,
			render_input: true,
		});
		c.set_value(value === undefined || value === null ? '' : ALP_TRIM_MICROSECONDS(value));
		c.refresh();
		this.fields[df.fieldname] = c;
		return c;
	}

	_val(f) { const c = this.fields[f]; return c ? c.get_value() : null; }

	_set(f, v) {
		const c = this.fields[f];
		if (c) { c.set_value(v === undefined || v === null ? '' : ALP_TRIM_MICROSECONDS(v)); c.refresh(); }
	}

	_toast(m, i) { frappe.show_alert({ message: m, indicator: i || 'blue' }, 5); }

	// ------------------------------------------------- BRD 2.1.1 header

	make_header_fields() {
		this._ctl('.field-name', {
			fieldname: 'name', label: 'Purchase Order ID', read_only: 1,
			description: 'Generated by the system on save.',
		});
		this._ctl('.field-inward-type', {
			fieldname: 'custom_inward_type', label: 'PO Type', fieldtype: 'Select',
			options: '\n' + PO_INWARD_TYPES.join('\n'), reqd: 1,
			description: 'Drives batch numbering and the QC checklist downstream.',
		});
		const me = this;
		const sup = this._ctl('.field-supplier', {
			fieldname: 'supplier', label: 'Vendor Name', fieldtype: 'Link',
			options: 'Supplier', reqd: 1,
		});
		if (sup && sup.$input) sup.$input.on('change', () => me.fetch_supplier());

		this._ctl('.field-transaction-date', {
			fieldname: 'transaction_date', label: 'PO Date', fieldtype: 'Date', reqd: 1,
		}, frappe.datetime.get_today());
		this._ctl('.field-schedule-date', {
			fieldname: 'schedule_date', label: 'Expected Delivery Date', fieldtype: 'Date', reqd: 1,
		});
		this._ctl('.field-set-warehouse', {
			fieldname: 'set_warehouse', label: 'Delivery Location', fieldtype: 'Link',
			options: 'Warehouse', reqd: 1,
		});
		this._ctl('.field-currency', {
			fieldname: 'currency', label: 'Currency', fieldtype: 'Link', options: 'Currency',
		});
		this._ctl('.field-payment-terms-template', {
			fieldname: 'payment_terms_template', label: 'Payment Terms',
			fieldtype: 'Link', options: 'Payment Terms Template',
		});
		this._ctl('.field-supplier-order-no', {
			fieldname: 'custom_supplier_order_no', label: 'Supplier Order No.',
			description: 'The reference the vendor quotes back on the invoice and challan.',
		});
		this._ctl('.field-buyer', {
			fieldname: 'owner', label: 'Buyer', fieldtype: 'Link', options: 'User', read_only: 1,
		}, frappe.session.user);
		this._ctl('.field-attachment', {
			fieldname: 'custom_inward_attachment', label: 'Attachment', fieldtype: 'Attach',
		});
		this._ctl('.field-direct-purchase-invoice', {
			fieldname: 'custom_direct_purchase_invoice', label: 'Direct Purchase Invoice',
			fieldtype: 'Check',
			description: 'Skips Purchase Inward, QC and GRN entirely (BR-PO-20 .. BR-PO-25).',
		});
		this._ctl('.field-remarks', {
			fieldname: 'custom_inward_remarks', label: 'Remarks', fieldtype: 'Small Text',
		});
	}

	// ------------------------------------------- BRD 2.2.2 supplier info

	make_supplier_fields() {
		const ro = (sel, fieldname, label, fieldtype, options) =>
			this._ctl(sel, {
				fieldname, label, fieldtype: fieldtype || 'Data', options, read_only: 1,
			});
		ro('.field-supplier-name', 'supplier_name', 'Vendor Name');
		ro('.field-contact-person', 'contact_person', 'Contact Person');
		ro('.field-contact-number', 'contact_mobile', 'Contact Number');
		ro('.field-billing-address', 'supplier_address', 'Billing Address');
		ro('.field-shipping-address', 'address_display', 'Shipping / Delivery Address', 'Small Text');
	}

	fetch_supplier() {
		const supplier = this._val('supplier');
		if (!supplier) return;
		const me = this;
		frappe.db.get_value('Supplier', supplier, ['supplier_name', 'supplier_primary_address'])
			.then((r) => {
				const d = (r && r.message) || {};
				me._set('supplier_name', d.supplier_name);
				me._set('supplier_address', d.supplier_primary_address);
			});
	}

	// --------------------------------------------- planned shipment block

	make_shipment_fields() {
		this._ctl('.field-vehicle-no', {
			fieldname: 'custom_vehicle_no', label: 'Vehicle Number',
			description: 'Data, not a number: vehicle references carry leading zeros and spaces.',
		});
		this._ctl('.field-driver-contact-no', {
			fieldname: 'custom_driver_contact_no', label: 'Driver Contact Number',
		});
		this._ctl('.field-estimated-arrival', {
			fieldname: 'custom_estimated_arrival', label: 'Estimated Arrival Date & Time',
			fieldtype: 'Datetime',
			// Without this the control appends the site time zone as a description.
			hide_timezone: 1,
			description: 'A date with no time is treated as 9:00 AM (BRD 2.1.1).',
		});
	}

	// -------------------------------------------------- BRD 2.3.2 summary

	make_summary_fields() {
		const ro = (sel, fieldname, label, fieldtype) =>
			this._ctl(sel, { fieldname, label, fieldtype: fieldtype || 'Currency', read_only: 1 });
		ro('.field-total-qty', 'total_qty', 'Total Item Quantity', 'Float');
		ro('.field-total', 'total', 'Total Item Value');
		ro('.field-total-discount', 'discount_amount', 'Total Discount');
		ro('.field-total-taxes', 'total_taxes_and_charges', 'Total Tax');
		ro('.field-grand-total', 'grand_total', 'Grand Total');
	}

	// ---------------------------------------------------- BRD 3 approval

	make_approval_fields() {
		const ro = (sel, fieldname, label, fieldtype, options) =>
			this._ctl(sel, {
				fieldname, label, fieldtype: fieldtype || 'Data', options, read_only: 1,
				hide_timezone: 1,
			});
		ro('.field-approval-status', 'custom_approval_status', 'Approval Status');
		ro('.field-approval-action-by', 'custom_approval_action_by', 'Approved / Rejected By',
			'Link', 'User');
		ro('.field-approval-datetime', 'custom_approval_datetime', 'Approval Date & Time', 'Datetime');
		ro('.field-approval-remarks', 'custom_approval_remarks', 'Approval Remarks', 'Small Text');
	}

	// ---------------------------------------------------- BRD 2.3.1 grid

	bind_events() {
		const me = this;
		this.wrapper.on('click', '.btn-add-row', () => me.add_row({}));
		this.wrapper.on('click', '.btn-remove-row', function () {
			const idx = cint($(this).closest('tr').attr('data-idx'));
			me.items.splice(idx, 1);
			me.redraw_items();
		});
	}

	add_row(row) {
		this.items.push(Object.assign({
			item_code: '', item_name: '', uom: '', qty: 0, price_list_rate: 0,
			discount_percentage: 0, rate: 0, amount: 0,
			schedule_date: this._val('schedule_date') || '',
			warehouse: this._val('set_warehouse') || '',
			custom_item_remarks: '',
		}, row || {}));
		this.redraw_items();
	}

	redraw_items() {
		const me = this;
		const $body = this.wrapper.find('.items-table tbody').empty();

		this.items.forEach((row, idx) => {
			const $tr = $(`
				<tr data-idx="${idx}">
					<td>${idx + 1}</td>
					<td class="cell-item-code"></td>
					<td class="cell-item-name"></td>
					<td class="cell-uom"></td>
					<td class="cell-qty"></td>
					<td class="cell-rate"></td>
					<td class="cell-discount"></td>
					<td class="cell-net-rate po-num"></td>
					<td class="cell-amount po-num"></td>
					<td class="cell-schedule"></td>
					<td class="cell-warehouse"></td>
					<td class="cell-remarks"></td>
					<td class="text-center">
						<button class="btn btn-xs btn-link btn-remove-row" title="Remove">
							<i class="fa fa-trash text-danger"></i>
						</button>
					</td>
				</tr>
			`);
			$body.append($tr);

			const mk = (sel, df, value, onchange) => {
				const c = frappe.ui.form.make_control({
					df: Object.assign({ fieldname: `${df.fieldname}_${idx}` }, df),
					parent: $tr.find(sel),
					render_input: true,
				});
				c.set_value(value === undefined || value === null ? '' : ALP_TRIM_MICROSECONDS(value));
				me.fields[`${df.fieldname}_${idx}`] = c;
				// Hand the handler the control PARSED value. The raw input text of a Date
				// control is the user format (dd-mm-yyyy) and reaches a DATE column as an
				// invalid date (MariaDB 1292).
				if (onchange && c.$input) c.$input.on('change', () => onchange(c.get_value()));
				return c;
			};

			mk('.cell-item-code', { fieldtype: 'Link', fieldname: 'item_code', options: 'Item' },
				row.item_code, (val) => {
					me.items[idx].item_code = val;
					me.fetch_item(idx, val);
				});
			mk('.cell-item-name', { fieldtype: 'Data', fieldname: 'item_name', read_only: 1 },
				row.item_name);
			mk('.cell-uom', { fieldtype: 'Data', fieldname: 'uom', read_only: 1 }, row.uom);
			mk('.cell-qty', { fieldtype: 'Float', fieldname: 'qty' },
				row.qty, (val) => { me.items[idx].qty = flt(val); me.recalc_row(idx); });
			// BRD 2.3.1 calls this Rate and defines Net Rate as "rate after applicable
			// discount". In ERPNext that pair is price_list_rate -> discount_percentage
			// -> rate, so BRD Rate binds to price_list_rate and BRD Net Rate to rate.
			// Binding the discount against `rate` instead does nothing at all: ERPNext
			// applies it to price_list_rate, so the discount column would be inert.
			mk('.cell-rate', { fieldtype: 'Currency', fieldname: 'price_list_rate' },
				row.price_list_rate, (val) => {
					me.items[idx].price_list_rate = flt(val);
					me.recalc_row(idx);
				});
			mk('.cell-discount', { fieldtype: 'Percent', fieldname: 'discount_percentage' },
				row.discount_percentage, (val) => {
					me.items[idx].discount_percentage = flt(val);
					me.recalc_row(idx);
				});
			mk('.cell-net-rate', { fieldtype: 'Currency', fieldname: 'rate', read_only: 1 },
				row.rate);
			mk('.cell-amount', { fieldtype: 'Currency', fieldname: 'amount', read_only: 1 },
				row.amount);
			mk('.cell-schedule', { fieldtype: 'Date', fieldname: 'schedule_date' },
				row.schedule_date, (val) => { me.items[idx].schedule_date = val; });
			mk('.cell-warehouse', { fieldtype: 'Link', fieldname: 'warehouse', options: 'Warehouse' },
				row.warehouse, (val) => { me.items[idx].warehouse = val; });
			mk('.cell-remarks', { fieldtype: 'Data', fieldname: 'custom_item_remarks' },
				row.custom_item_remarks, (val) => { me.items[idx].custom_item_remarks = val; });
		});
	}

	fetch_item(idx, item_code) {
		if (!item_code) return;
		const me = this;
		frappe.db.get_value('Item', item_code, ['item_name', 'stock_uom']).then((r) => {
			const d = (r && r.message) || {};
			me.items[idx].item_name = d.item_name || '';
			me.items[idx].uom = d.stock_uom || '';
			me.redraw_items();
		});
	}

	/** Preview only. The ERP recomputes on save and the saved values win. */
	recalc_row(idx) {
		const row = this.items[idx];
		const net = flt(row.price_list_rate) * (1 - flt(row.discount_percentage) / 100);
		row.rate = net;
		row.amount = net * flt(row.qty);
		const nr = this.fields[`rate_${idx}`];
		const am = this.fields[`amount_${idx}`];
		if (nr) nr.set_value(ALP_TRIM_MICROSECONDS(row.rate));
		if (am) am.set_value(ALP_TRIM_MICROSECONDS(row.amount));
	}

	// ------------------------------------------------------ approval log

	render_approval_log() {
		const rows = (this.doc && this.doc.custom_approval_log) || [];
		const $body = this.wrapper.find('.approval-table tbody').empty();
		rows.forEach((r, i) => {
			$body.append($(`
				<tr>
					<td>${i + 1}</td>
					<td>${frappe.utils.escape_html(r.approval_status || '')}</td>
					<td>${frappe.utils.escape_html(r.action_by || '')}</td>
					<td>${frappe.utils.escape_html(String(r.action_on || '').split('.')[0])}</td>
					<td>${frappe.utils.escape_html(r.previous_status || '')}</td>
					<td>${frappe.utils.escape_html(r.new_status || '')}</td>
					<td>${frappe.utils.escape_html(r.remarks || '')}</td>
				</tr>
			`));
		});
	}

	// ----------------------------------------------------- route / load

	handle_route_entry() {
		const route = frappe.get_route() || [];
		const name = route[1] || (frappe.route_options && frappe.route_options.purchase_order);
		if (frappe.route_options) delete frappe.route_options.purchase_order;
		if (name && name !== this.docname) {
			this.load(name);
		} else if (!name && this.docname) {
			// Opened bare after viewing an order: the previous one must not linger.
			this.reset();
		}
	}

	reset() {
		this.docname = null;
		this.doc = null;
		this.items = [];
		this.wrapper.find('tbody').empty();
		[
			'custom_inward_type', 'supplier', 'schedule_date', 'set_warehouse', 'currency',
			'payment_terms_template', 'custom_supplier_order_no', 'custom_inward_attachment',
			'custom_direct_purchase_invoice', 'custom_inward_remarks', 'supplier_name',
			'contact_person', 'contact_mobile', 'supplier_address', 'address_display',
			'custom_vehicle_no', 'custom_driver_contact_no', 'custom_estimated_arrival',
			'total_qty', 'total', 'discount_amount', 'total_taxes_and_charges', 'grand_total',
			'custom_approval_status', 'custom_approval_action_by', 'custom_approval_datetime',
			'custom_approval_remarks', 'name',
		].forEach((f) => this._set(f, ''));
		this._set('transaction_date', frappe.datetime.get_today());
		this._set('owner', frappe.session.user);
		this.page.set_title(__('Purchase Order Entry'));
		this.apply_state();
	}

	load(name) {
		const me = this;
		frappe.call({
			method: 'frappe.client.get',
			args: { doctype: 'Purchase Order', name: name },
			freeze: true,
			callback(r) {
				if (!r.message) return;
				const doc = r.message;
				me.docname = doc.name;
				me.doc = doc;
				[
					'name', 'custom_inward_type', 'supplier', 'transaction_date', 'schedule_date',
					'set_warehouse', 'currency', 'payment_terms_template',
					'custom_supplier_order_no', 'owner', 'custom_inward_attachment',
					'custom_direct_purchase_invoice', 'custom_inward_remarks',
					'supplier_name', 'contact_person', 'contact_mobile', 'supplier_address',
					'address_display', 'custom_vehicle_no', 'custom_driver_contact_no',
					'custom_estimated_arrival', 'total_qty', 'total', 'discount_amount',
					'total_taxes_and_charges', 'grand_total', 'custom_approval_status',
					'custom_approval_action_by', 'custom_approval_datetime',
					'custom_approval_remarks',
				].forEach((f) => me._set(f, doc[f]));

				me.items = (doc.items || []).map((row) => Object.assign({}, row));
				me.redraw_items();
				me.render_approval_log();
				me.apply_state();
				me.page.set_title(`${doc.name} — Purchase Order`);
			},
		});
	}

	apply_state() {
		const doc = this.doc || {};
		const status = doc.custom_approval_status || '';
		const $root = this.wrapper.find('.purchase-order-entry');
		$root.toggleClass('po-saved', !!this.docname);

		const $badge = this.wrapper.find('.field-stage-badge')
			.text(status)
			.removeClass('po-approved po-rejected po-waiting');
		if (status === 'Approved' || status === 'Sent to Supplier') $badge.addClass('po-approved');
		else if (status === 'Rejected' || status === 'Cancelled') $badge.addClass('po-rejected');
		else if (status === 'Pending Approval') $badge.addClass('po-waiting');

		// VAL-PO-08 / BR-PO-12: an order awaiting approval, or already submitted, is
		// not the Purchase Team to edit any more. The server refuses it either way;
		// this only stops the screen inviting an edit that cannot be saved.
		const locked = cint(doc.docstatus) !== 0 || status === 'Pending Approval';
		this.wrapper.find('.eso-card').not('.po-approval-card').toggleClass('po-locked', locked);

		this.make_actions();
	}

	// ------------------------------------------------- BRD 2.3.3 actions

	make_actions() {
		const me = this;
		const $bar = this.wrapper.find('.po-actionbar').empty();
		const doc = this.doc || {};
		const status = doc.custom_approval_status || '';
		const editable = cint(doc.docstatus) === 0 && status !== 'Pending Approval';

		const btn = (label, cls, handler) => {
			$(`<button class="btn btn-sm ${cls}" style="margin-left:8px;">${frappe.utils.escape_html(label)}</button>`)
				.on('click', handler)
				.appendTo($bar);
		};

		if (editable) btn(__('Save'), 'btn-primary', () => me.save());

		if (this.docname) {
			// The approval transitions come from the server so the two can never drift.
			frappe.call({
				method: 'alpinos.purchase.purchase_order_approval.get_available_actions',
				args: { purchase_order: this.docname },
				callback(r) {
					const actions = (r.message && r.message.actions) || [];
					actions.forEach((a) => {
						btn(__(a.action), 'btn-primary', () => me.run_action(a.action));
					});
					btn(__('Print'), 'btn-light', () => {
						frappe.set_route('print', 'Purchase Order', me.docname);
					});
				},
			});
		} else {
			$bar.append(
				`<span class="text-muted">${__('Fill the header and at least one item line, then Save.')}</span>`
			);
		}
	}

	run_action(action) {
		const me = this;
		const needs_remarks = action === 'Reject';
		const takes_remarks = needs_remarks || action === 'Return for Correction';

		const call = (remarks) => frappe.call({
			method: 'alpinos.purchase.purchase_order_approval.perform_action',
			args: { purchase_order: me.docname, action: action, remarks: remarks },
			freeze: true,
			freeze_message: __('Updating the Purchase Order...'),
			callback(r) { if (r.exc) return; me.load(me.docname); },
		});

		if (!takes_remarks) {
			frappe.confirm(__('{0} this Purchase Order?', [__(action)]), () => call(null));
			return;
		}
		const d = new frappe.ui.Dialog({
			title: __(action),
			fields: [{
				fieldname: 'remarks', label: __('Remarks'), fieldtype: 'Small Text',
				reqd: needs_remarks ? 1 : 0,
			}],
			primary_action_label: __(action),
			primary_action(values) { d.hide(); call(values.remarks); },
		});
		d.show();
	}

	// ------------------------------------------------------------- save

	_payload() {
		return {
			custom_inward_type: this._val('custom_inward_type'),
			supplier: this._val('supplier'),
			transaction_date: this._val('transaction_date'),
			schedule_date: this._val('schedule_date'),
			set_warehouse: this._val('set_warehouse'),
			currency: this._val('currency') || undefined,
			payment_terms_template: this._val('payment_terms_template') || undefined,
			custom_supplier_order_no: this._val('custom_supplier_order_no'),
			custom_inward_attachment: this._val('custom_inward_attachment'),
			custom_direct_purchase_invoice: cint(this._val('custom_direct_purchase_invoice')),
			custom_inward_remarks: this._val('custom_inward_remarks'),
			custom_vehicle_no: this._val('custom_vehicle_no'),
			custom_driver_contact_no: this._val('custom_driver_contact_no'),
			custom_estimated_arrival: this._val('custom_estimated_arrival'),
			items: this.items.map((row) => ({
				item_code: row.item_code,
				qty: flt(row.qty),
				price_list_rate: flt(row.price_list_rate),
				discount_percentage: flt(row.discount_percentage),
				schedule_date: row.schedule_date || this._val('schedule_date'),
				warehouse: row.warehouse || this._val('set_warehouse'),
				custom_item_remarks: row.custom_item_remarks,
			})),
		};
	}

	save() {
		const me = this;
		if (!this.items.length) {
			frappe.msgprint({
				title: __('No Items'),
				message: __('Please add at least one item to the Purchase Order.'),
				indicator: 'red',
			});
			return;
		}
		const payload = this._payload();

		if (this.docname) {
			frappe.call({
				method: 'frappe.client.get',
				args: { doctype: 'Purchase Order', name: this.docname },
				callback(r) {
					const doc = Object.assign({}, r.message, payload);
					frappe.call({
						method: 'frappe.client.save',
						args: { doc: doc },
						freeze: true,
						freeze_message: __('Saving...'),
						callback(res) {
							if (!res.message) return;
							me._toast(__('Saved'), 'green');
							me.load(res.message.name);
						},
					});
				},
			});
			return;
		}

		frappe.call({
			method: 'frappe.client.insert',
			args: { doc: Object.assign({ doctype: 'Purchase Order' }, payload) },
			freeze: true,
			freeze_message: __('Creating the Purchase Order...'),
			callback(r) {
				if (!r.message) return;
				me._toast(__('Purchase Order {0} created', [r.message.name]), 'green');
				frappe.set_route('purchase_order_entry', r.message.name);
				me.load(r.message.name);
			},
		});
	}
};
